extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.to_ssa]
pipeline = [
    "bril2json",
    "python3 to_ssa.py",
    "brili -p {args}",
]

[runs.from_ssa]
pipeline = [
    "bril2json",
    "python3 to_ssa.py",
    "python3 from_ssa.py",
    "brili -p {args}",
]